//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiSeguros.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaDir
    {
        public int IdPersona { get; set; }
        public int CodTipoDir { get; set; }
        public int CodPais { get; set; }
        public int CodProvincia { get; set; }
        public string TxtCallePrin { get; set; }
        public string TxtCalleSec { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
        public string TxtLugrReferencia { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual TipoDireccion TipoDireccion { get; set; }
    }
}
